apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: app
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: api
        property: db_url
    - secretKey: DB_USER
      remoteRef:
        key: api
        property: db_user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: api
        property: db_password
    - secretKey: API_KEY
      remoteRef:
        key: api
        property: api_key
