server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /parcels {
    resolver __RESOLVER__ valid=30s ipv6=off;
    set $api __API_URL__;
    proxy_pass $api;
    proxy_set_header Host $host;
  }
}
